name: test
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  rspec:
    name: rspec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.9-bookworm # heroku postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cfp_app_test
    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/cfp_app_test
    steps:
      - run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl libvips postgresql-client libpq-dev imagemagick

      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: bundle exec rails db:setup
      - run: bundle exec rspec
          cache: 'yarn'

      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres@localhost:5432/cfp_app_test
        run: bundle e rails db:setup assets:precompile spec

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/capybara
          if-no-files-found: ignore
